import type { Metadata } from 'next';
import Link from 'next/link';
import {
  COMPANY_NAME,
  SITE_NAME,
  SUPPORT_EMAIL,
  SUPPORT_URL
} from '@/src/lib/constants';

export const metadata: Metadata = {
  title: `Privacy Policy — ${SITE_NAME}`,
  description:
    `Privacy policy for ${SITE_NAME}, operated by ${COMPANY_NAME}. Learn how we handle your data and your rights as a user.`
};

export default function PrivacyPage() {
  return (
    <article
      aria-labelledby="privacy-title"
      className="mx-auto max-w-3xl px-6 pb-16 pt-10 text-sm leading-relaxed text-mutedForeground"
    >
      <header className="mb-6 border-b border-border/70 pb-4">
        <p className="text-[11px] uppercase tracking-[0.3em] text-buzzr-accent/80">
          Legal
        </p>
        <h1
          id="privacy-title"
          className="mt-2 font-heading text-3xl text-foreground md:text-4xl"
        >
          Privacy Policy
        </h1>
        <p className="mt-2 text-[12px] text-mutedForeground">
          Last updated: February 27, 2026
        </p>
      </header>

      <div className="space-y-6 rounded-2xl border border-border/70 bg-buzzr-surface/60 p-5 shadow-soft backdrop-blur">
        <p>
          This Privacy Policy explains how {COMPANY_NAME} (&quot;we&quot;,
          &quot;us&quot;, or &quot;our&quot;) collects, uses, and protects your
          information in connection with the Buzzr Sports mobile and web
          applications (collectively, the &quot;Service&quot;).
        </p>

        <section aria-labelledby="section-data-we-collect" className="space-y-2">
          <h2 id="section-data-we-collect" className="text-base font-semibold text-foreground">
            1. Information we collect
          </h2>
          <p>When you use Buzzr Sports, we may collect:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>
              <strong>Account and profile information</strong> such as your name,
              email address, and basic settings you choose in the app.
            </li>
            <li>
              <strong>Usage information</strong> about how you interact with the
              Service, including actions such as rating games, saving favorites,
              or following other users (if enabled).
            </li>
            <li>
              <strong>Device and log information</strong> such as IP address,
              device type, operating system, app version, and diagnostics
              information generated by the app or hosting platform.
            </li>
          </ul>
        </section>

        <section aria-labelledby="section-how-we-use" className="space-y-2">
          <h2 id="section-how-we-use" className="text-base font-semibold text-foreground">
            2. How we use your information
          </h2>
          <p>We use your information to:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Provide, operate, and improve the Service.</li>
            <li>
              Personalize your experience, such as remembering which games you
              have rated or watched.
            </li>
            <li>
              Communicate with you about updates, support requests, and important
              notices related to the Service.
            </li>
            <li>
              Monitor performance, debug issues, and keep the Service secure.
            </li>
          </ul>
        </section>

        <section aria-labelledby="section-analytics" className="space-y-2">
          <h2 id="section-analytics" className="text-base font-semibold text-foreground">
            3. Analytics and third-party services
          </h2>
          <p>
            We may use privacy-conscious analytics providers or hosting platforms
            (such as Vercel or similar) that process limited technical data (for
            example, request logs and performance metrics) to help us understand
            how the Service is used and to keep it reliable.
          </p>
        </section>

        <section aria-labelledby="section-data-retention" className="space-y-2">
          <h2 id="section-data-retention" className="text-base font-semibold text-foreground">
            4. Data retention
          </h2>
          <p>
            We retain your information for as long as necessary to provide the
            Service and for legitimate business and legal purposes, such as
            maintaining records, resolving disputes, and enforcing our agreements.
          </p>
        </section>

        <section aria-labelledby="section-rights" className="space-y-2">
          <h2 id="section-rights" className="text-base font-semibold text-foreground">
            5. Your rights and choices
          </h2>
          <p>You may have rights under applicable data protection laws, such as:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Requesting access to or a copy of the personal data we hold.</li>
            <li>Requesting correction or deletion of your information.</li>
            <li>Objecting to or restricting certain types of processing.</li>
          </ul>
          <p>
            To exercise these rights, contact us using the email in the{' '}
            <strong>Contact us</strong> section below. We may need to verify your
            identity before responding to your request.
          </p>
        </section>

        <section aria-labelledby="section-children" className="space-y-2">
          <h2 id="section-children" className="text-base font-semibold text-foreground">
            6. Children&apos;s privacy
          </h2>
          <p>
            Buzzr Sports is not directed to children under the age required by law
            in your jurisdiction, and we do not knowingly collect personal data
            from children without appropriate parental consent where required.
          </p>
        </section>

        <section aria-labelledby="section-changes" className="space-y-2">
          <h2 id="section-changes" className="text-base font-semibold text-foreground">
            7. Changes to this policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time. When we do, we
            will update the &quot;Last updated&quot; date at the top of this
            page. Material changes may also be communicated in-app or by email.
          </p>
        </section>

        <section aria-labelledby="section-contact" className="space-y-2">
          <h2 id="section-contact" className="text-base font-semibold text-foreground">
            8. Contact us
          </h2>
          <p>
            If you have questions about this Privacy Policy or how your data is
            handled, you can reach us at:
          </p>
          <address className="not-italic">
            {COMPANY_NAME}
            <br />
            Email:{' '}
            <a className="underline" href={`mailto:${SUPPORT_EMAIL}`}>
              {SUPPORT_EMAIL}
            </a>
          </address>
          <p>
            You can also contact us via our{' '}
            <Link className="underline" href={SUPPORT_URL}>
              support page
            </Link>
            .
          </p>
        </section>
      </div>
    </article>
  );
}
