import type { Metadata } from 'next';
import Link from 'next/link';
import {
  BASE_URL,
  COMPANY_NAME,
  SITE_NAME,
  SUPPORT_EMAIL,
  SUPPORT_URL
} from '@/src/lib/constants';

const PAGE_TITLE = `Privacy Policy · ${SITE_NAME}`;
const PAGE_DESCRIPTION = `Privacy policy for ${SITE_NAME}, operated by ${COMPANY_NAME}. Learn how we handle your data and your rights as a user.`;

export const metadata: Metadata = {
  title: PAGE_TITLE,
  description: PAGE_DESCRIPTION,
  alternates: { canonical: '/privacy' },
  openGraph: {
    type: 'article',
    url: `${BASE_URL}/privacy`,
    siteName: SITE_NAME,
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION
  },
  twitter: {
    card: 'summary',
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION,
    site: '@the_real_buzzr'
  }
};

export default function PrivacyPage() {
  return (
    <article
      aria-labelledby="privacy-title"
      className="mx-auto max-w-3xl px-6 pb-16 pt-10 text-sm leading-relaxed text-muted"
    >
      <>
        <header className="mb-8 border-b border-surface/70 pb-5">
          <p className="text-[11px] uppercase tracking-[0.3em] text-foreground">
            Legal
          </p>
          <h1
            id="privacy-title"
            className="mt-2 font-sans text-3xl text-foreground md:text-4xl"
          >
            Privacy Policy
          </h1>
          <p className="mt-2 text-[12px] text-muted">
            Last updated: February 27, 2026
          </p>
        </header>
      </>

      <div className="space-y-8 rounded-2xl border border-surface/70 bg-surface p-6 backdrop-blur sm:p-8">
        <>
          <p>
            This Privacy Policy explains how {COMPANY_NAME} (&quot;we&quot;,
            &quot;us&quot;, or &quot;our&quot;) collects, uses, and protects your
            information in connection with the Buzzr Sports mobile and web
            applications (collectively, the &quot;Service&quot;).
          </p>
        </>

        <>
          <section aria-labelledby="section-data-we-collect" className="space-y-2">
            <h2 id="section-data-we-collect" className="text-base font-semibold text-foreground">
              1. Information we collect
            </h2>
            <p>When you use Buzzr Sports, we may collect:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong className="text-foreground">Account and profile information</strong> such as your name,
                email address, and basic settings you choose in the app.
              </li>
              <li>
                <strong className="text-foreground">Usage information</strong> about how you interact with the
                Service, including actions such as rating games, saving favorites,
                or following other users (if enabled).
              </li>
              <li>
                <strong className="text-foreground">Device and log information</strong> such as IP address,
                device type, operating system, app version, and diagnostics
                information generated by the app or hosting platform.
              </li>
            </ul>
          </section>
        </>

        <>
          <section aria-labelledby="section-how-we-use" className="space-y-2">
            <h2 id="section-how-we-use" className="text-base font-semibold text-foreground">
              2. How we use your information
            </h2>
            <p>We use your information to:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>Provide, operate, and improve the Service.</li>
              <li>
                Personalize your experience, such as remembering which games you
                have rated or watched.
              </li>
              <li>
                Communicate with you about updates, support requests, and important
                notices related to the Service.
              </li>
              <li>
                Monitor performance, debug issues, and keep the Service secure.
              </li>
            </ul>
          </section>
        </>

        <>
          <section aria-labelledby="section-analytics" className="space-y-2">
            <h2 id="section-analytics" className="text-base font-semibold text-foreground">
              3. Analytics and third-party services
            </h2>
            <p>
              We may use privacy-conscious analytics providers or hosting platforms
              (such as Vercel or similar) that process limited technical data (for
              example, request logs and performance metrics) to help us understand
              how the Service is used and to keep it reliable.
            </p>
          </section>
        </>

        <>
          <section aria-labelledby="section-data-retention" className="space-y-2">
            <h2 id="section-data-retention" className="text-base font-semibold text-foreground">
              4. Data retention
            </h2>
            <p>
              We retain your information for as long as necessary to provide the
              Service and for legitimate business and legal purposes, such as
              maintaining records, resolving disputes, and enforcing our agreements.
            </p>
          </section>
        </>

        <>
          <section aria-labelledby="section-rights" className="space-y-2">
            <h2 id="section-rights" className="text-base font-semibold text-foreground">
              5. Your rights and choices
            </h2>
            <p>You may have rights under applicable data protection laws, such as:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>Requesting access to or a copy of the personal data we hold.</li>
              <li>Requesting correction or deletion of your information.</li>
              <li>Objecting to or restricting certain types of processing.</li>
            </ul>
            <p>
              To exercise these rights, contact us using the email in the{' '}
              <strong className="text-foreground">Contact us</strong> section below. We may need to verify your
              identity before responding to your request.
            </p>
          </section>
        </>

        <>
          <section aria-labelledby="section-children" className="space-y-2">
            <h2 id="section-children" className="text-base font-semibold text-foreground">
              6. Children&apos;s privacy
            </h2>
            <p>
              Buzzr Sports is not directed to children under the age required by law
              in your jurisdiction, and we do not knowingly collect personal data
              from children without appropriate parental consent where required.
            </p>
          </section>
        </>

        <>
          <section aria-labelledby="section-changes" className="space-y-2">
            <h2 id="section-changes" className="text-base font-semibold text-foreground">
              7. Changes to this policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. When we do, we
              will update the &quot;Last updated&quot; date at the top of this
              page. Material changes may also be communicated in-app or by email.
            </p>
          </section>
        </>

        <>
          <section aria-labelledby="section-contact" className="space-y-2">
            <h2 id="section-contact" className="text-base font-semibold text-foreground">
              8. Contact us
            </h2>
            <p>
              If you have questions about this Privacy Policy or how your data is
              handled, you can reach us at:
            </p>
            <address className="not-italic">
              {COMPANY_NAME}
              <br />
              Email:{' '}
              <a className="text-foreground underline underline-offset-3 transition-colors hover:text-muted" href={`mailto:${SUPPORT_EMAIL}`}>
                {SUPPORT_EMAIL}
              </a>
            </address>
            <p>
              You can also contact us via our{' '}
              <Link className="text-foreground underline underline-offset-3 transition-colors hover:text-muted" href={SUPPORT_URL}>
                support page
              </Link>
              .
            </p>
          </section>
        </>
      </div>
    </article>
  );
}
